FROM  nickgryg/alpine-pandas:3.7.4

RUN apk add --no-cache build-base libexecinfo-dev

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt


COPY . /app

# start app (only for the demos of the hackdays, use real webserver or similar later)
CMD ["/app/server.py"]
